### ISSUE TITLE
Beautiful integration of images, but...

### ISSUE THREAD

**Issue by Grizz5678** [miccl/MMM-Random-local-image#10]
I love everything about this module, but so far in the instructions I haven't managed to find a way to remove the title of the image which shows up underneath the picture on the magic mirror. I can't imagine anyone wanting to see a filename on their magic mirror. Is there a way to add/remove code so that it doesn't show up on the mirror? 
![_image000000_](https://user-images.githubusercontent.com/32799929/193166955-85595a13-55ef-4b5f-b0e7-61158e6ef744.jpg)

**Comment by stutoni** [comment]
I am using mmm-remote-control module to control my mirror and there I can uncomment a setting called : showAdditionalInformation

**Comment by Grizz5678** [comment]
I didn't try to "uncomment". I think you mean "comment" in js with //? The module instructions say that you need to define as false instead, so that's what I did. I will try what you are suggesting but by default it is supposed to be true so we will have to see.

**Comment by stutoni** [comment]
![mmm-localphoto](https://user-images.githubusercontent.com/91457638/193565098-40c02f12-072b-417d-b7c8-d8d4e9d99543.jpg)
this is how it looks in remotecontrol

**Comment by miccl** [comment]
hi @Grizz5678, glad you enjoy this module :)
if you want to hide the file path, you need to set the configuration `showAddtionalInformation` in your config settings (as your already guessed correctly).

here my configuration as an reference (however with it enabled): 
```
{
     module: 'MMM-Random-local-image',
     position: 'bottom_right',
          config: {
               photoDir: './modules/MMM-Random-local-image/nfs_image_cloud',
               photoLoadInitialDelay: 5000,
               photoUpdateInterval: 20 * 1000,
               selectFromSubdirectories: true,
               maxWidth: '28em',
               maxHeight: '28em',
               ignoreDirRegex: '^Sonstiges',
               showAdditionalInformation: true
          }
     },
```
I enriched the readme with more details.
if it still doesnt work, just reopen this ticket.
Greets Michael
