### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Andrzej15** [miccl/MMM-Random-local-image#11]
Hello 
how do I put a title for the Pictures in the Config File?
Does your module accept title or header?

Thanks

**Comment by miccl** [comment]
Hi @Andrzej15,

If I understand correctly, you're interested in adding a header above the displayed pictures. 
The `header` field in the Magic Mirror configuration for a module could serve this purpose.
You can configure it like this:

```javascript

modules: [
  {
    module: "MMM-Random-local-image",
    position: "fullscreen_below",
    header: "Some header here",
    config: {
      // Configuration options for the module
    },
  },
];
```

For more detailed information, you can refer to the [Module Configuration](https://docs.magicmirror.builders/modules/configuration.html) documentation.

Tell me if the solution works for me.

Greets 
Michael
