### ISSUE TITLE
[Suggestion] Fix module compatibility with CSS override

### ISSUE THREAD

**Issue by SMNFXCN** [miccl/MMM-Random-local-image#12]
Hi,
I am using MMM-OnSpotify with this module, and it has a feature to do a custom css override, changing the color of certain elements.
With the relative path options enabled, the path text is dark grey, I tried to get this module working with it until I discovered a fix. On [Line 90 of the module's .js file](https://github.com/miccl/MMM-Random-local-image/blob/d1454096053206a1116a51f127ac1245f9f884b9/MMM-Random-local-image.js#L90), if you change
`element.className = "dimm small regular";` to `element.className = "dimmed small regular";`, it lets the path text be compatible with MMM-OnSpotify's CSS override.

**Comment by miccl** [comment]
Hey @SMNFXCN,
Sorry for the late response! I’ve fixed it.
Thanks for reporting the issue and especially for investigating how to resolve it :)

Best regards,
Michi
