### ISSUE TITLE
Not seeing pics

### ISSUE THREAD

**Issue by w2rgh** [miccl/MMM-Random-local-image#7]
Only seeing text of path/filename

![Capture](https://user-images.githubusercontent.com/77648696/134747705-01e6cf5e-4738-4e31-a88d-4be0a9a4e066.PNG)

**Comment by miccl** [comment]
The problem probably is your photoDir path definition. 
I only tested relative paths from the magic mirror dir.
Can you try the default path:  `./modules/MMM-Random-local-image/photos/` and see if the images are shown.

**Comment by w2rgh** [comment]
Solved but now new issue with rotation screen is portrait photos are landscape.

**Comment by miccl** [comment]
Hi, the problem with the rotating images is on electrons side.
See the this created issue in another lib: https://github.com/AdamMoses-GitHub/MMM-ImageSlideshow/issues/15.
I would close this issue.
